model_type: transformer_native # ['transformer', 'transformer_native']
K: 4
transformer: 
    d_model: 256
    n_head: 4
    num_layers: 2
optim:
    type: sgd
    lr: 
        type: const # ['const']
        init_lr: 1e-2
        warm_up: True
        warmup_steps: 10 # used omly when warm_up is True
    momentum: 0.99
    weight_decay: 0
    nesterov: true
    # type: AdamW
    # lr: 
    #     type: const
    #     init_lr: 1e-3
    #     warm_up: True
    #     warmup_steps: 10
    # beta1: 0.91
    # beta2: 0.98

train:
    p: 97
    alpha: 0.8
    batch_size: 512
    epochs: 720
    # dropout: 0.9
  
