model_type: transformer # ['transformer', 'transformer_native']
K: 3
transformer: 
    d_model: 128
    n_head: 4
    num_layers: 2
optim:
    type: sgd
    lr: 
        type: const # ['const']
        init_lr: 3e-2
        warm_up: True
        warmup_steps: 10 # used omly when warm_up is True
    momentum: 0.99
    weight_decay: 0
    nesterov: true

train:
    p: 97
    alpha: 0.5
    batch_size: 512
    epochs: 500
  
