model_type: transformer # ['transformer', 'transformer_native']
transformer: 
    d_model: 128
    n_head: 4
    num_layers: 2
optim:
    type: sgd
    lr: 
        type: const # ['const']
        init_lr: 1e-3
        warm_up: True
        warmup_steps: 10 # used omly when warm_up is True
    momentum: 0.99
    nesterov: true
    weight_decay: 0 

train:
    p: 97
    alpha: 0.5
    batch_size: 512
    epochs: 10000
  
